#!/bin/sh
set -e

# write the php-fpm config
#{ \
#    echo listen = /var/run/php-fpm.sock; \
#    echo listen.owner = www-data; \
#    echo listen.group = www-data; \
#    echo pm.max_children = "$FPM_PM_MAX_CHILDREN"; \
#    echo pm.start_servers = "$FPM_PM_START_SERVERS"; \
#    echo pm.min_spare_servers = "$FPM_PM_MIN_SPARE_SERVERS"; \
#    echo pm.max_spare_servers = "$FPM_PM_MAX_SPARE_SERVERS"; \
#} > /usr/local/etc/php-fpm.d/zzz-app.conf

if [ ! -f /etc/nginx/ssl/ssl.key ]; then
    echo "🔐 Generating a self-signed SSL certificate because one was not provided..."
    mkdir -p /etc/nginx/ssl/
    openssl req -x509 -subj "/C=KE/ST=Mombasa/L=Mombasa/O=Ecobiz/CN=localhost" -nodes -newkey rsa:2048 -keyout /etc/nginx/ssl/ssl.key -out /etc/nginx/ssl/ssl.crt -days 365
fi

exec "$@"
